### ISSUE TITLE
Allow classerloader to be injected

### ISSUE THREAD

**Issue by thedarkcder** [magneticflux-/ortools-java#5]
Current method of loading doesn't work on all platforms i.e aws

Request additional method to specify classloader such spring ResourceLoader

**Comment by magneticflux-** [comment]
This should be an easy fix since I already implemented it upstream.

I don't have much experience with cloud services like AWS, could you show a log of what happens when the wrong classloader is used?

**Comment by thedarkcder** [comment]
Log 
`Caused by: java.nio.file.NoSuchFileException: /BOOT-INF/lib/ortools-natives-linux-7.5.7466.jar!/linux-x86-64/`

I normally fix this using the Spring resource loader

**Comment by magneticflux-** [comment]
Okay, that makes sense since Spring uses a servlet that loads dependencies differently (OSGi maybe?). I'll merge #6 which should let you use whatever `ClassLoader` you want. It'll be available at `com.skaggsm.ortools:ortools-natives-all:7.5.7467` soon.

**Comment by thedarkcder** [comment]
Ahh no luck - without using the spring resource loader directly and only the classloader i believe it is missing the prefix "classpath:" 

shouldn't make any different to loading

**Comment by magneticflux-** [comment]
I don't quite understand, could you explain more of what's going wrong? How are you loading the jar and what's the whole stack trace of the error you're getting?

**Comment by thedarkcder** [comment]
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.nio.file.NoSuchFileException: /BOOT-INF/lib/ortools-natives-linux-7.5.7467.jar!/linux-x86-64/
	at com.sun.nio.zipfs.ZipPath.getAttributes(ZipPath.java:666)
	at com.sun.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:294)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.Files.walkFileTree(Files.java:2662)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.skaggsm.ClasspathUtils.lambda$extractResources$0(ClasspathUtils.java:38)
	at com.skaggsm.ClasspathUtils.visitUriAsPath(ClasspathUtils.java:72)
	at com.skaggsm.ClasspathUtils.extractResources(ClasspathUtils.java:36)
	at com.skaggsm.ClasspathUtils.extractResourcesToTempDirectory(ClasspathUtils.java:19)
	at com.skaggsm.ortools.OrToolsHelper.loadLibrary(OrToolsHelper.kt:26)
	at com.skaggsm.ortools.OrToolsHelper.loadLibrary(OrToolsHelper.kt:18)
	at com.skaggsm.ortools.OrToolsHelper.loadLibrary$default(OrToolsHelper.kt:17)
	at com.skaggsm.ortools.OrToolsHelper.loadLibrary(OrToolsHelper.kt)
	at org.aprilavenue.api.SpringBootApp.main(SpringBootApp.java:131)
	... 8 more
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.nio.file.NoSuchFileException: /BOOT-INF/lib/ortools-natives-linux-7.5.7467.jar!/linux-x86-64/
	at com.sun.nio.zipfs.ZipPath.getAttributes(ZipPath.java:666)
	at com.sun.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:294)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.Files.walkFileTree(Files.java:2662)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.skaggsm.ClasspathUtils.lambda$extractResources$0(ClasspathUtils.java:38)
	at com.skaggsm.ClasspathUtils.visitUriAsPath(ClasspathUtils.java:72)
	at com.skaggsm.ClasspathUtils.extractResources(ClasspathUtils.java:36)
	at com.skaggsm.ClasspathUtils.extractResourcesToTempDirectory(ClasspathUtils.java:19)
	at com.skaggsm.ortools.OrToolsHelper.loadLibrary(OrToolsHelper.kt:26)
	at com.skaggsm.ortools.OrToolsHelper.loadLibrary(OrToolsHelper.kt:18)
	at com.skaggsm.ortools.OrToolsHelper.loadLibrary$default(OrToolsHelper.kt:17)
	at com.skaggsm.ortools.OrToolsHelper.loadLibrary(OrToolsHelper.kt)
	at org.aprilavenue.api.SpringBootApp.main(SpringBootApp.java:131)
	... 8 more


Jar is loaded through maven 

now using the Spring ResourceLoader 

package org.springframework.core.io;

import org.springframework.lang.Nullable;

```
public interface ResourceLoader {
    String CLASSPATH_URL_PREFIX = "classpath:";

    Resource getResource(String var1);

    @Nullable
    ClassLoader getClassLoader();
}



```


Looking at the stack trace I think the prefix of "classpath:" is needed.  I believe this is a Spring 2 issue.

**Comment by magneticflux-** [comment]
I think this comes from having the dependencies packaged inside an "uber-jar". Spring Boot puts dependencies in the final jar under `/BOOT-INF/lib/xyz.jar`, which is in turn inside `/myapp.jar` that you can deploy. There doesn't seem to be a way to extract from nested jar files without extracting the jar files one-at-a-time.

One possible workaround is to deploy your dependencies outside of your jar. This has some benefits to caching in a container environment as well, since only your jar changes on recompile.

**Comment by riochr17** [comment]
i have the same issue on spring-boot
`Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.nio.file.NoSuchFileException: /BOOT-INF/lib/ortools-natives-macos-7.5.7467.jar!/darwin
at jdk.zipfs/jdk.nio.zipfs.ZipPath.getAttributes(ZipPath.java:723)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:293)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1755)
        at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
        at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2705)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2785)
        at com.skaggsm.ClasspathUtils.lambda$extractResources$0(ClasspathUtils.java:38)
        at com.skaggsm.ClasspathUtils.visitUriAsPath(ClasspathUtils.java:72)
        at com.skaggsm.ClasspathUtils.extractResources(ClasspathUtils.java:36)
        at com.skaggsm.ClasspathUtils.extractResourcesToTempDirectory(ClasspathUtils.java:19)
        at com.skaggsm.ortools.OrToolsHelper.loadLibrary(OrToolsHelper.kt:26)
        at com.skaggsm.ortools.OrToolsHelper.loadLibrary(OrToolsHelper.kt:18)
        at com.skaggsm.ortools.OrToolsHelper.loadLibrary$default(OrToolsHelper.kt:17)
        at com.skaggsm.ortools.OrToolsHelper.loadLibrary(OrToolsHelper.kt)
        at id.wistaone.appbudget.AppbudgetApplication.main(AppbudgetApplication.java:13)
        ... 8 more`

it is running well on VSCode using debugger, but got error on jar built with gradle 
`> ./gradlew clean build
> java -jar build/libs/my-spring-boot-app-0.0.1-SNAPSHOT.jar
> here errors happen`

i don't really understand how VSCode run the java but it running well using this command (generated by VSCode):
`/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:53846 -Dfile.encoding=UTF-8 @/var/folders/qr/npk9mlf56f58230vk3j1w0x80000gn/T/cp_3jx6nu7sf8zj93zo3f5dm01rv.argfile MySpringBootApplicationClass`

Environtment

Java
`java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)`

Gradle
`------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          9 (Oracle Corporation 9+181)
OS:           Mac OS X 10.15.4 x86_64`

**Comment by riochr17** [comment]
This is may be ugly solution to solve this problem, but it works anyway.

1. Download release Google OR Tool from [https://github.com/google/or-tools/releases](https://github.com/google/or-tools/releases)
2. Extract (it should has ```/lib``` folder)
3. Build jar using gradle
```
> ./gradlew clean build
> java -jar build/libs/my-spring-boot-app-0.0.1-SNAPSHOT.jar
> here errors happen
```
3. Run java and give reference to libary path
```
> java -Djava.library.path=<path-to-extracted-lib> -jar build/libs/my-spring-boot-app-0.0.1-SNAPSHOT.jar
```

**Comment by magneticflux-** [comment]
See my previous comment https://github.com/magneticflux-/ortools-java/issues/5#issuecomment-623245302.

I'll rephrase it here:

A `java.nio` Filesystem is required to enumerate arbitrary classpaths that may or may not be inside a jar.

- In production, Spring Boot packages jars inside other jars and this **doesn't** work with `java.nio` ZipFilesystem. This is why doesn't work deployed.

- In development, Gradle just loads plain folders of classes and resources instead of jars and this **does** work with `java.nio` Filesystems. This is why it works in your IDE.

These are the two workarounds discussed:
1. Don't package jars inside other jars. Load them separately through some other means, i.e. "[exploding](https://docs.spring.io/spring-boot/docs/current/reference/html/deployment.html#containers-deployment)" them for [containerization](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#building-docker-images).
2. Just install Or-Tools how Google recommends it, without a Maven dependency.

I mentioned workaround #​1 briefly in my previous comment.
@riochr17 your workaround is basically workaround #​2. You might as well just extract the jar file along with the native libs and add it as a filetree dependency.

**Comment by C-Otto** [comment]
For me it helped to use a Spring Boot feature built into the gradle plugin that seems to be tailored to this issue (tested with Google's library, `implementation 'com.google.ortools:ortools-java:9.3.10497'`):

```
bootJar {
    requiresUnpack '**/ortools-darwin*.jar', '**/ortools-win32*.jar', '**/ortools-linux*.jar'
}
```
